routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Clientes;
use App\Mecanico;
use App\Trasporte;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if(Auth::user()){
        return view('home');
    }
    return view('auth.login');
});
Route::get('opciones', function () {
    $mecanicos=Mecanico::all();
    $clientes=Clientes::all();
    $trasportes=Trasporte::all();
    $data=[
        'trasportes'=>$trasportes,
        'mecanicos'=>$mecanicos,
        'clientes'=>$clientes
    ];
    return view('ordentrabajo.create',compact('data'));
});
Route::resource('produ_orden', 'ProductoOrdenController');
Route::resource('refa_orden', 'RefaccionOrdenController');
Route::resource('almacen', 'AlmacenController');
Route::resource('/Clientes', 'ClienteController');
Route::resource('/herramientas', 'HerramientasTallerController');
Route::resource('/producto', 'ProductoReparacionController');
Route::resource('/refaccion', 'RefaccionController');
Route::resource('/trabajo', 'TrabajoDefinidoController');
Route::resource('/descuento', 'DescuentoController');
Route::resource('/automovil', 'AutomovilController');
Route::resource('/mecanico', 'MecanicoController');
Route::resource('/ordentrabajo', 'OrdenTrabajoController');
Route::resource('/estado', 'EstadoController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('users/{id}', function ($id) {
    
});

resources/views/producto/create.blade.php
@extends('layouts.app')
@section('content')
<form action="{{ route('herramientas.store') }}" method="post">
@csrf
<div class="container">
    <div class="row">
        <div class="col-xl-6">
            <div class="form-group">
                <label for="codigo_barra">Codigo de Barra *</label>
                <input type="text" class="form-control" name="codigo_barra" id="codigo_barra" placeholder="Codigo de barra" required>
            </div>
        </div>
        <div class="col-xl-6">
            <div class="form-group">
                <label for="nombre">Nombre *</label>
                <input type="text" class="form-control" name="nombre" id="nombre" placeholder="Nombre" required>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="form-group">
              <label for="descripcion">Descripcion *</label>
              <textarea class="form-control" name="descripcion" id="descripcion" rows="3" required></textarea>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-3">
            <div class="form-group">
                <label for="tipo_unidad">Tipo Unidad *</label>
                <input type="text" class="form-control" name="tipo_unidad" id="tipo_unidad" placeholder="Tipo de unidad" required>
            </div>
        </div>
        <div class="col-xl-3">
            <div class="form-group">
                <label for="cantidad">Cantidad *</label>
                <input type="text" class="form-control" name="cantidad" id="cantidad" placeholder="Cantidad" required>
            </div>
        </div>
        <div class="col-xl-3">
            <div class="form-group">
                <label for="costo_compra">Costo Compra *</label>
                <input type="text" class="form-control" name="costo_compra" id="costo_compra" placeholder="Costo Compra" required>
            </div>
        </div>
        <div class="col-xl-3">
            <div class="form-group">
                <label for="costo_venta">Costo Venta *</label>
                <input type="text" class="form-control" name="costo_venta" id="costo_venta" placeholder="Costo Venta" required>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-info">Crear</button>
</div>
</form>
@endsection

resources/views/producto/orden.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <form action="{{route('produ_orden.store')}}" method="post">
        @csrf
        <?php
            $id=$_GET['idOrdenTrabajo'];
        ?>
        <input type="hidden" name="idOrdenTrabajo" value="{{$id}}">
        <div class="row">
            <div class="col-xl-1-4">
                <div class="form-group">
                  <label for="idProductoReparacion">Producto</label>
                  <select class="form-control" name="idProductoReparacion" id="idProductoReparacion">
                    @foreach ($productos as $item)
                        <option value="{{$item->id}}">{{$item->nombre}}---{{$item->descripcion}}</option>
                    @endforeach
                  </select>
                </div>
            </div>
            <div class="col-xl-4-7">
                <div class="form-group">
                  <label for="cantidad">Cantidad</label>
                  <input type="number"
                    class="form-control" name="cantidad" id="cantidad" placeholder="Cantidad">
                </div>
            </div>
            <div class="col-xl-7-12 p-4">
                <button type="submit" class="btn btn-info">Agregar</button>
            </div>
        </div>
    </form>
</div>
@endsection