routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Clientes;
use App\Mecanico;
use App\Trasporte;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if(Auth::user()){
        return view('home');
    }
    return view('auth.login');
});
Route::get('opciones', function () {
    $mecanicos=Mecanico::all();
    $clientes=Clientes::all();
    $trasportes=Trasporte::all();
    $data=[
        'trasportes'=>$trasportes,
        'mecanicos'=>$mecanicos,
        'clientes'=>$clientes
    ];
    return view('ordentrabajo.create',compact('data'));
});
Route::resource('produ_orden', 'ProductoOrdenController');
Route::resource('refa_orden', 'RefaccionOrdenController');
Route::resource('almacen', 'AlmacenController');
Route::resource('/Clientes', 'ClienteController');
Route::resource('/herramientas', 'HerramientasTallerController');
Route::resource('/producto', 'ProductoReparacionController');
Route::resource('/refaccion', 'RefaccionController');
Route::resource('/trabajo', 'TrabajoDefinidoController');
Route::resource('/descuento', 'DescuentoController');
Route::resource('/automovil', 'AutomovilController');
Route::resource('/mecanico', 'MecanicoController');
Route::resource('/ordentrabajo', 'OrdenTrabajoController');
Route::resource('/estado', 'EstadoController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('users/{id}', function ($id) {
    
});

app/OrdenTrabajo.php
<?php

namespace App;
use App\ProductoReparacionOrdenTrabajo;
use App\RefaccionOrdenTrabajo;
use App\TrabajoDefinidoOrdenTrabajo;
use App\EstadoOrdenTrabajo;
use App\Mecanico;
use App\Trasporte;
use App\Clientes;

use Illuminate\Database\Eloquent\Model;

class OrdenTrabajo extends Model
{
    //
    protected $fillable = [
        'idCliente','tipo_orden','idTrasporte','esterio','cb','antena_cb','barras_cont','vcr',
        'monitores','maleteros','ceniceros','funda_asientos','serie_orden_de_trabajo',
        'fechaEmision','FechaPrometida','idEstadoOrden','reporteInicial','obcervaciones','idMecanico',
        'kilometraje'
    ];

    public function productoReparacionOrdenT(){
        return $this->belongsToMany(ProductoReparacionOrdenTrabajo::class);
    }
    public function refaccionOrdenT(){
        return $this->belongsToMany(RefaccionOrdenTrabajo::class);
    }
    public function trabajoDefinidoOrdenT(){
        return $this->belongsToMany(TrabajoDefinidoOrdenTrabajo::class);
    }
    public function estadoOrdenT(){
        return $this->hasMany(EstadoOrdenTrabajo::class);
    }
    public function mecanico(){
        return $this->hasMany(Mecanico::class);
    }
    public function trasporte(){
        return $this->hasMany(Trasporte::class);
    }
    public function cliente(){
        return $this->hasMany(Clientes::class);
    }
}

app/Http/Controllers/OrdenTrabajoController.php
<?php

namespace App\Http\Controllers;

use App\Clientes;
use App\EstadoOrdenTrabajo;
use App\Trasporte;
use App\OrdenTrabajo;
use App\TrabajoDefinido;
use Illuminate\Http\Request;
use Intervention\Image\Image;

class OrdenTrabajoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $ordenT=OrdenTrabajo::all();
        $estados=[];
        foreach ($ordenT as $orden) {
            array_push($estados,EstadoOrdenTrabajo::latest()->where('idOrden',$orden->id)->first());
        }

        return view('ordentrabajo.index',compact('ordenT','estados'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $trabajo=TrabajoDefinido::all();
        $data=[
            'trabajo'=>$trabajo,
        ];

        if($_GET['customRadioInline1']=='carro_chico'){
            return view('ordentrabajo.carro_chico',compact('data'));
        }
        if($_GET['customRadioInline1']=='carro_grande'){
            return view('ordentrabajo.carro_grande',compact('data'));
        }
        if($_GET['customRadioInline1']=='van'){
            return view('ordentrabajo.furgo',compact('data'));
        }
        if($_GET['customRadioInline1']=='trailer'){
            return view('ordentrabajo.trailer',compact('data'));
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // \dd($request);
        $img = $_POST['base64'];
        $img = str_replace('data:image/png;base64,', '', $img);
        $fileData = base64_decode($img);
        $fileName = "img/orden_trabajo/".uniqid().'.png';
        
        file_put_contents($fileName, $fileData);
        // \dd($request->all());

        // $request->validate([
        //     'idCliente'=>'required',
        //     'idTrasporte'=>'required',
        //     'idMecanico'=>'required',
        //     'kilometraje'=>'required',
        //     'tanque'=>'required',
        //     'serie_orden_de_trabajo'=>'required',
        // ]);
        //guardar y mover imagen
        $oren=OrdenTrabajo::create($request->except('_token'));
        $oren->base64=$fileName;
        $oren->save();
        $estado=new EstadoOrdenTrabajo;
        $estado->idOrden = $oren->id;
        $estado->estado = 'REGISTRADO';
        $estado->save();
        //dd("orden :",$oren,"estado:",$estado);
        return \redirect()->route('ordentrabajo.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $ordenT=OrdenTrabajo::find($id);
        return view('ordentrabajo.show',compact('ordenT'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/ordentrabajo/carro_chico.blade.php
@extends('layouts.app')
@section('content')
<form action="{{ Route('ordentrabajo.store') }}" method="post" ENCTYPE='multipart/form-data' id="formCan">
    @csrf
<div class="container">
    <div class="row">
        <div class="col-xl-2 col-sm-2 align-items-center">
            <div class="form-group">
                <?php
                    $meca=$_GET['idMecanico'];
                ?><label for="idMecanico">Mecanico: </label>
                <input type="text" class="form-control" name="idMecanico" id="idMecanico" value='{{ $meca }}' onkeydown="event.preventDefault();">
            </div>
        </div>
        <div class="col-xl-2 col-sm-2 align-items-center">
            <div class="form-group">
                <?php
                    $clien=$_GET['idCliente'];
                ?><label for="idCliente">Cliente :</label>
              <input type="text" class="form-control" name="idCliente" id="idCliente" value="{{ $clien }}"  onkeydown="event.preventDefault();">
            </div>
        </div>
        <div class="col-xl-2 col-sm-2 align-items-center">
            <div class="form-group">
                <?php
                    $tras=$_GET['idTrasporte'];
                ?><label for="idTrasporte">Trasporte :</label>
                <input type="text" class="form-control" name="idTrasporte" id="idTrasporte" value="{{ $tras }}" onkeydown="event.preventDefault();">
            </div>
        </div>
    </div>
    <div class="row tarlogin">
        <!--checkBox-->
        <div class="col-xl-5 col-sm-5 align-items-center">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="normal" name="customRadioInline1" class="custom-control-input">
                <label class="custom-control-label" for="normal">Normal</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="rescate" name="customRadioInline1" class="custom-control-input">
                <label class="custom-control-label" for="rescate">Rescate</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="garantia" name="customRadioInline1" class="custom-control-input">
                <label class="custom-control-label" for="garantia">Garantia</label>
            </div>
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="r&g" name="customRadioInline1" class="custom-control-input">
                <label class="custom-control-label" for="r&g">R&G Ambos</label>
            </div>
        </div>
        <div class="col-xl-5 col-sm-5 align-self-end">
            <!--<p id=demo></p>-->
            <input type="text" name="serie_orden_de_trabajo" id="serie_orden_de_trabajo" placeholder="Serie" onkeydown="event.preventDefault();">
            <button type="button" onclick="randomQuote();"> Generar Orden Serie</button>
        </div>
    </div>
</div>
<!--Canvas-->
<div class="container">
    <div class="row">
        <div class="col-12">
            <button type="button" onclick="change();">draw image</button>
        </div>
    </div>
        <div class="d-none">
            <img src="{{ asset('img/canvas/CheckCarroChico.PNG') }}" id="dummy" class="carroChico" alt="">
        </div>
    <div class="row d-flex">
        <div class="col-xl-6 col-xs-12">
            <canvas id="micanvas" class="canvas-cr"
                onmousemove="pintar(event);" onmouseup="desactivar();" onmousedown="activar();" onload="change();">
            </canvas>
            <input type="hidden" name="base64" value="" id="base64">
        </div>
        <!--CheckList-->
        <div class="col-xl-6 col-xs-12">
            <div id="checkList" role="tablist" aria-multiselectable="true">
                <div class="card">
                    <div class="card-header" role="tab" id="section1HeaderId">
                        <h5 class="mb-0">
                            <a data-toggle="collapse" data-parent="#checkList" href="#section1ContentId" aria-expanded="true" aria-controls="section1ContentId">
                      Check Lists
                    </a>
                        </h5>
                    </div>
                    <div id="section1ContentId" class="collapse in" role="tabpanel" aria-labelledby="section1HeaderId">
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="esterio" name="esterio">
                                        <label class="custom-control-label" for="esterio">Esterio</label>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="cb" name="cb">
                                        <label class="custom-control-label" for="cb">CB</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="antena_cb" name="antena_cb">
                                        <label class="custom-control-label" for="antena_cb">Antena CB</label>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="barras_cont" name="barras_cont">
                                        <label class="custom-control-label" for="barras_cont">Barras Cont</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="vcr" name="vcr">
                                        <label class="custom-control-label" for="vcr">VCR</label>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="monitores" name="monitores">
                                        <label class="custom-control-label" for="monitores">monitores</label>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="ceniceros" name="ceniceros">
                                        <label class="custom-control-label" for="ceniceros">Ceniceros</label>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" class="custom-control-input" id="funda_asientos" name="funda_asientos">
                                        <label class="custom-control-label" for="funda_asientos">Funda Asientos</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 pt-2">
                    <div class="form-group">
                        <input type="text" class="form-control" name="kilometraje" id="kilometraje" placeholder="kilometraje">
                    </div>
                </div>
                <div class="col-6">
                    <map name="tanque">
                        <area shape="rect" coords="4,60,35,81" onclick="area1();" alt="tanque 1">
                        <area shape="rect" coords="16,30,42,55" onclick="area2();" alt="tanque 2">
                        <area shape="rect" coords="48,9,71,51" onclick="area3();" alt="tanque 3">
                        <area shape="rect" coords="75,5,93,36" onclick="area4();" alt="tanque 4">
                        <area shape="rect" coords="101,4,120,41" onclick="area5();" alt="tanque 5">
                        <area shape="rect" coords="124,6,147,34" onclick="area6();" alt="tanque 6">
                        <area shape="rect" coords="155,21,178,51" onclick="area7();" alt="tanque 7">
                        <area shape="rect" coords="177,37,198,62" onclick="area8();" alt="tanque 8">
                        <area shape="rect" coords="181,57,213,83" onclick="area9();" alt="tanque 9">
                    </map>
                    <img src="{{ asset('img/tanque/T1.jpg') }}" alt="tanque" usemap="#tanque" id="imgtanque">
                    <input type="hidden" name="tanque" id="tanque" value="">
                </div>
            </div>
            <div class="row pt-4">
                <div class="col-12">
                    <label for="fechaEmision">Fecha Emitida</label>
                    <input type="date" name="fechaEmision" id="fechaEmision">
                </div>
                <div class="col-12">
                    <label for="FechaPrometida">Fecha Prometida</label>
                    <input type="date" name="FechaPrometida" id="FechaPrometida">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                      <label for="reporteInicial">Reporte Inicial</label>
                      <textarea class="form-control" name="reporteInicial" id="reporteInicial" rows="4"></textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                      <label for="trabajodefinido">Trabajo Definido</label>
                      <select  class="form-control form-control-sm" name="trabajodefinido" id="trabajodefinido">
                        @foreach ($data['trabajo'] as $traba)
                            <option value="{{$traba->nombre}}">{{$traba->nombre}},{{$traba->descripcion}}</option>
                        @endforeach
                      </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="form-group">
                        <label for="obcervaciones">Observaciones</label>
                        <textarea class="form-control" name="obcervaciones" id="obcervaciones" rows="4"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <button id="saveandfinish" class="btn btn-info" onclick="guardar();">Guardar</button>
        </div>
    </div>
</div>
</form>
@endsection

resources/views/ordentrabajo/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="container tarlogin">
            <div class="row">
                <div class="col-12 aling-right">
                    <button class="btn" type="button" data-toggle="collapse"
                     data-target="#collapseExample" aria-expanded="true" aria-controls="collapseExample"
                     style="width: 50px; height: 30px;" >
                          <img class="card-img-top" src="{{ asset('img/minimiza.svg')}}" alt="">
                    </button>
                </div>
            </div>
            <form action="" method="post">
                @csrf
                <div class="row" id="collapseExample">
                    <div class="col-4">
                        <div class="form-group">
                            <label for="no_cliente">No.Cliente</label>
                            <input type="text"
                            class="form-control" name="no_cliente" id="no_cliente" placeholder="Numero Cliente">
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                        <label for="mecanico">Mecanico</label>
                        <input type="text" class="form-control" name="mecanico" id="mecanico" placeholder="Mecanico">
                        </div>
                    </div>
                    <div class="col-3 align-self-center pt-3">
                        <button type="submit" class="btn btn-light">Buscar</button>
                    </div>
                </div>
            </form>
        </div>
        <br>
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <a class="btn btn-light border border-primary" href="/opciones" role="button">Nueva Orden de Trabajo</a>
                </div>
            </div>
        </div>
        <br>
        <div class="container-fluid">
            <table class="table table-hover table-inverse table-responsive">
                <thead class="thead-inverse">
                    <tr>
                        <th>Id Mecanico</th>
                        <th>Id Cliente</th>
                        <th>Id Trasporte</th>
                        <th>Serie Orden Trabajo</th>
                        <th>Estado</th>
                        <th rowspan="4">Opciones</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($ordenT as $t)
                            <tr>
                                <td>{{$t->idMecanico}}</td>
                                <td>{{$t->idCliente}}</td>
                                <td>{{$t->idTrasporte}}</td>
                                <td>{{$t->serie_orden_de_trabajo}}</td>
                                @foreach ($estados as $estado)
                                    <td>{{$estado->estado}}</td>
                                @endforeach
                                <td>
                                    <form action="{{route('ordentrabajo.show',$t->id)}}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-info btn-sm">Ver</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{route('produ_orden.create')}}" method="GET">
                                        @csrf
                                        <input type="hidden" name="idOrdenTrabajo" value="{{$t->id}}">
                                        <button type="submit" class="btn btn-light border border-primary btn-sm">Agregar Producto</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{route('refa_orden.create')}}" method="GET">
                                        @csrf
                                        <input type="hidden" name="idOrdenTrabajo" value="{{$t->id}}">
                                        <button type="submit" class="btn btn-light border border-primary btn-sm">Agregar Refaccion</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{route('estado.store')}}" method="POST">
                                        @csrf
                                        <input type="hidden" name="idOrden" value="{{$t->id}}">
                                        <button type="submit" class="btn btn-light border border-primary btn-sm">Cambiar Estado</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
            </table>
        </div>
    </div>
@endsection