routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Clientes;
use App\Mecanico;
use App\Trasporte;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if(Auth::user()){
        return view('home');
    }
    return view('auth.login');
});
Route::get('opciones', function () {
    $mecanicos=Mecanico::all();
    $clientes=Clientes::all();
    $trasportes=Trasporte::all();
    $data=[
        'trasportes'=>$trasportes,
        'mecanicos'=>$mecanicos,
        'clientes'=>$clientes
    ];
    return view('ordentrabajo.create',compact('data'));
});
Route::resource('produ_orden', 'ProductoOrdenController');
Route::resource('refa_orden', 'RefaccionOrdenController');
Route::resource('almacen', 'AlmacenController');
Route::resource('/Clientes', 'ClienteController');
Route::resource('/herramientas', 'HerramientasTallerController');
Route::resource('/producto', 'ProductoReparacionController');
Route::resource('/refaccion', 'RefaccionController');
Route::resource('/trabajo', 'TrabajoDefinidoController');
Route::resource('/descuento', 'DescuentoController');
Route::resource('/automovil', 'AutomovilController');
Route::resource('/mecanico', 'MecanicoController');
Route::resource('/ordentrabajo', 'OrdenTrabajoController');
Route::resource('/estado', 'EstadoController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('users/{id}', function ($id) {
    
});

app/Clientes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Descuento;
use App\Trasporte;
class Clientes extends Model
{
    //
    protected $fillable = [
        'nombre','apellido_p','apellido_m','rfc','forma_pago','dirección','colonia','codigo_postal',
        'ciudad','telefono','celular','email','observaciones','no_cliente'
    ];

    public function descuento(){
        return $this->belongsToMany(Descuento::class);
    }

    public function trasportes(){
        return $this->hasMany(Trasporte::class);
    }
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Clientes;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $clientes=Clientes::all();
        return view('Clientes.index',compact('clientes'));
        //return view('Clientes.buscar',compact('clientes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $enums=explode("','",substr(DB::select('SHOW COLUMNS FROM '."clientes"." LIKE 'forma_pago'")[0]->Type,6,-2));
        return view('Clientes.create',compact('enums'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        //dd($request);
        //exit();
        $request->validate([

            'nombre' => 'required',
            'rfc' => 'required',
            'forma_pago' => 'required',
            'dirección' => 'required',
            'colonia' => 'required',
            'codigo_postal'=>'integer',
            'ciudad' => 'required',
            'email'=>'required',
            'no_cliente'=>'required',
        ]);

        $clientes=Clientes::create($request->except('_token'));
        $clientes->save();

        return \redirect()->route('Clientes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $cliente=Clientes::find($id);
        $enums=explode("','",substr(DB::select('SHOW COLUMNS FROM '."clientes"." LIKE 'forma_pago'")[0]->Type,6,-2));
        $data=[
            'cliente'=>$cliente,
            'enums'=>$enums,
        ];
        return view('clientes.show',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $cliente=Clientes::find($id);
        $cliente->delete();

        return \redirect()->route('Clientes.index');
    }
}

resources/views/clientes/buscar.blade.php
@extends('layouts.app')
@section('content')
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <a class="btn btn-light border border-primary" href="{{Route('Clientes.create')}}" role="button">Nuevo Cliente</a>
                </div>
            </div>
        </div>
        <br>
        <div class="container">
            <table class="table table-hover table-inverse table-responsive">
                <thead class="thead-inverse">
                    <tr>
                        <th>NO.Cliente</th>
                        <th>Nombre</th>
                        <th>Apellido P</th>
                        <th>Apellido M</th>
                        <th>RFC</th>
                        <th>Opcion</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($clientes as $cliente)
                        <tr>
                            <td>{{ $cliente->no_cliente}}</td>
                            <td>{{ $cliente->nombre}}</td>
                            <td>{{ $cliente->apellido_p}}</td>
                            <td>{{ $cliente->apellido_m}}</td>
                            <td>{{ $cliente->rfc}}</td>
                            <td>
                                <button type="button" name="" id="cliente_{{ $cliente->id }}" onclick="selccionarCliente(this.id);" class="btn btn-info btn-sm btn-block">Seleccionar</button>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/clientes/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
    <div class="container">
        <form action="{{ Route('Clientes.store')}}" method="post">
            @csrf
            <div class="form-group">
                <div class="row">
                    <div class="col-4">
                        <label for="no_cliente">No.Cliente *</label>
                        <input type="text" name="no_cliente" id="no_cliente" class="form-control" placeholder="Numero Cliente" required>
                    </div>
                    <div class="col-4">
                        <label for="rfc">RFC *</label>
                        <input type="text" name="rfc" id="rfc" class="form-control" placeholder="RFC" required>
                    </div>
                    <div class="col-4">
                        <label for="nombre">Nombre *</label>
                        <input type="text" name="nombre" id="nombre" class="form-control" placeholder="Nombre" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <label for="apellido_p">Apellido P</label>
                        <input type="text" name="apellido_p" id="apellido_p" class="form-control" placeholder="Apellido Paterno">
                    </div>
                    <div class="col-4">
                        <label for="apellido_m">Apellido M</label>
                        <input type="text" name="apellido_m" id="apellido_m" class="form-control" placeholder="Apellido Materno">
                    </div>
                    <div class="col-4">
                        <label for="forma_pago">Forma de Pago *</label>
                        <select class="form-control" name="forma_pago" id="forma_pago" required>
                            @foreach ($enums as $enum)
                                <option>{{$enum}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <label for="dirección">Dirección *</label>
                        <input type="text" name="dirección" id="dirección" class="form-control" placeholder="Dirección" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <label for="colonia">Colonia * </label>
                        <input type="text" name="colonia" id="colonia" class="form-control" placeholder="Direccion" required>
                    </div>
                    <div class="col-4">
                        <label for="codigo_postal">Codigo Postal *</label>
                        <input type="text" name="codigo_postal" id="codigo_postal" class="form-control" placeholder="codigo postal" required>
                    </div>
                    <div class="col-4">
                        <label for="ciudad">Ciudad *</label>
                        <input type="text" name="ciudad" id="ciudad" class="form-control" placeholder="Ciudad" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <label for="telefono">Telefono</label>
                        <input type="text"class="form-control" name="telefono" id="telefono" placeholder="Telefono">
                    </div>
                    <div class="col-4">
                        <label for="movil">Movil</label>
                        <input type="text"class="form-control" name="movil" id="movil" placeholder="Telefono">
                    </div>
                    <div class="col-4">
                        <label for="email">Email *</label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="Correo Electronico" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-12">
                        <div class="form-group">
                          <label for="observaciones">Observaciones</label>
                          <textarea class="form-control" name="observaciones" id="observaciones" rows="5"></textarea>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-info">Registrar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="container tarlogin">
            <div class="row">
                <div class="col-12 aling-right">
                    <button class="btn" type="button" data-toggle="collapse"
                     data-target="#collapseExample" aria-expanded="true" aria-controls="collapseExample"
                     style="width: 50px; height: 30px;" >
                          <img class="card-img-top" src="{{ asset('img/minimiza.svg')}}" alt="">
                    </button>
                </div>
            </div>
            <form action="" method="post">
                @csrf
                <div class="row" id="collapseExample">
                    <div class="col-4">
                        <div class="form-group">
                            <label for="no_cliente">No.Cliente</label>
                            <input type="text"
                            class="form-control" name="no_cliente" id="no_cliente" placeholder="Numero Cliente">
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                        <label for="rfc">RFC</label>
                        <input type="text" class="form-control" name="rfc" id="rfc" placeholder="RFC">
                        </div>
                    </div>
                    <div class="col-3 align-self-center pt-3">
                        <button type="submit" class="btn btn-light">Buscar</button>
                    </div>
                </div>
            </form>
        </div>
        <br>
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <a class="btn btn-light border border-primary" href="{{Route('Clientes.create')}}" role="button">Nuevo Cliente</a>
                </div>
            </div>
        </div>
        <br>
        <div class="container">
            <table class="table table-hover table-inverse table-responsive">
                <thead class="thead-inverse">
                    <tr>
                        <th>NO.Cliente</th>
                        <th>Nombre</th>
                        <th>Apellido P</th>
                        <th>Apellido M</th>
                        <th>RFC</th>
                        <th rowspan="2">Opciones</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach ($clientes as $cliente)
                        <tr>
                            <td>{{ $cliente->no_cliente}}</td>
                            <td>{{ $cliente->nombre}}</td>
                            <td>{{ $cliente->apellido_p}}</td>
                            <td>{{ $cliente->apellido_m}}</td>
                            <td>{{ $cliente->rfc}}</td>
                            <td>
                                <form action="{{ route('Clientes.show',$cliente->id) }}" method="get">
                                    @csrf
                                    <button type="submit" class="btn btn-info">Ver</button>
                                </form>
                            </td>
                            <td>
                                <form action="{{ route('Clientes.destroy',$cliente->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                        <input type="hidden" name="id" id="id" value="{{ $cliente->id }}">
                                    <button type="submit" class="btn btn-danger">Eliminar</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/clientes/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <form action="" method="post">
            <div class="form-group">
                <div class="row">
                    <div class="col-4">
                        <label for="rfc">RFC </label>
                        <input type="text" name="rfc" id="rfc" class="form-control" placeholder="RFC" value="{{ $data['cliente']->rfc }}" disabled>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="forma_pago">Metodo Pago</label>
                            <select class="custom-select" name="forma_pago" id="forma_pago">
                                <option selected>{{ $data['cliente']->forma_pago }}</option>
                                @foreach ($data['enums'] as $enum)
                                    <option>{{$enum}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-4">
                        <label for="nombre">Nombre </label>
                        <input type="text" name="nombre" id="nombre" class="form-control" placeholder="Nombre" value="{{ $data['cliente']->nombre }}" >
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <label for="apellido_p">Apellido P</label>
                        <input type="text" name="apellido_p" id="apellido_p" class="form-control" placeholder="Apellido Paterno" value="{{ $data['cliente']->apellido_p }}">
                    </div>
                    <div class="col-6">
                        <label for="apellido_m">Apellido M</label>
                        <input type="text" name="apellido_m" id="apellido_m" class="form-control" placeholder="Apellido Materno" value="{{ $data['cliente']->apellido_m }}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <label for="dirección">Dirección *</label>
                        <input type="text" name="dirección" id="dirección" class="form-control" placeholder="Dirección" value="{{ $data['cliente']->dirección }}" >
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <label for="colonia">Colonia  </label>
                        <input type="text" name="colonia" id="colonia" class="form-control" placeholder="Direccion" value="{{ $data['cliente']->colonia }}" >
                    </div>
                    <div class="col-4">
                        <label for="codigo_postal">Codigo Postal</label>
                        <input type="text" name="codigo_postal" id="codigo_postal" class="form-control" placeholder="codigo postal" value="{{ $data['cliente']->codigo_postal }}">
                    </div>
                    <div class="col-4">
                        <label for="ciudad">Ciudad </label>
                        <input type="text" name="ciudad" id="ciudad" class="form-control" placeholder="Ciudad" value="{{ $data['cliente']->ciudad }}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <label for="telefono">Telefono</label>
                        <input type="text"class="form-control" name="telefono" id="telefono" placeholder="Telefono" value="{{ $data['cliente']->telefono }}">
                    </div>
                    <div class="col-4">
                        <label for="movil">Movil</label>
                        <input type="text"class="form-control" name="movil" id="movil" placeholder="celular" value="{{ $data['cliente']->movil }}">
                    </div>
                    <div class="col-4">
                        <label for="email">Email </label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="Correo Electronico" value="{{ $data['cliente']->email }}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="form-group">
                            <label for="observaciones">Observaciones</label>
                            <textarea class="form-control" name="observaciones" id="observaciones" rows="5">{{ $data['cliente']->observaciones }}</textarea>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-info" disabled>Modificar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection